#user container-based infrastructure
sudo: false
before_install:
# install dependencies
  - pip install robotframework
  - robot --version
  - pip install robotframework-selenium2library
install: "pip install -r requirements.txt"
language: python
python:
  - "2.7"
script: pybot SearchGoogle.robot