#user container-based infrastructure
sudo: false
before_install:
# install dependencies
  - pip install robotframework
  - pip install robotframework-selenium2library

install: "pip install -r requirements.txt"
language: python
python:
  - "2.7"

env:
  global:
    - export PATH=/usr/local/bin/:$PATH

script: pybot SearchGoogle.robot