#user container-based infrastructure
sudo: false
before_install:
# install dependencies
  - pip install robotframework
  - pip install robotframework-selenium2library

install: "pip install -r requirements.txt"
language: python
python:
  - "2.7"

env:
  global:
    - PATH =  /home/travis/virtualenv/python2.7.14/lib/python2.7/
    - export PATH=/usr/local/bin/:$PATH

script: pabot SearchGoogle.robot